VARIABLE LABELS
M01 "M01 Nom de l'enquêteur"
/M02 "M02 Numéro de la tablette"
/M03 "M03 Date"
/M05 "M05 Votre lieu actuel"
/M06 "M06 Quartier ou vous devez travailler aujourd'hui"
/M07 "M07 Avenue la plus proche"
/M08 "M08 Capturer les coordonnées GPS"
/M09 "M09 Comment se passe la collecte de donées?"
/M10 "M10 Ca ne se passe pas trop bien? Nous sommes la pour aider. Avez-vous contacté votre superviseur ou quelqu'un d'autre? Decrivez-ci dessous les problemes principaux."
/M11 "M11 Passons au travail de la journee. Quel est le niveau de la batterie de la tablette?"
/M12 "M12 Merci, bonne continuation"
/start "Start"
/end "End"
/today "Today"
/deviceid "DeviceID"
/username "Username"
/instanceID "instanceID"
/uuid "uuid"

VALUE LABELS
/M01 anonymized1 "Anonymized label" anonymized2 "Anonymized label."
/M05 1 "Goma" 2 "Masisi" 3 "Bukavu" 4 "Kalehe"
/M09 1 "Très bien" 2 "Bien" 3 "Moyen" 4 "Mal" 5 "Très mal"
/M11 1 "Plein - bon travail" 2 "Environ 3/4 - bon travail, il faudra recharger ce soir!" 3 "50% - bon travail, mais verifiez d'etat de la batterie avant chaque interview. Il faudra absolument recharger ce soir" 4 "1/4 - vous pourrez faire une interview au plus. verifiez le niveau durant l'interview et termine lorsqu'un point d'exclamation apparait" 5 "Moins d'1/4 ou '!' - sauvegarder votre travail et rechargez immediatement."
